server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: walljs111
    url: jdbc:mysql://localhost:3306/db_cloud_user?useSSL=false
  application:
    name: userservice
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.yg.cloud.user.pojo

logging:
  level:
    com.yg: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

