server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_cloud_user?useSSL=false
    password: walljs111
    username: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.yg.cloud.user.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.yg: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
