server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: walljs111
    url: jdbc:mysql://localhost:3306/db_cloud_order?useSSL=false
mybatis:
  type-aliases-package: com.yg.cloud.order.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.yg: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
